name: Backend CI

on:
  push:
    branches:
      - main
      - taskfeatures
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show backend files
        run: |
          pwd
          ls
          ls test

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test